version: '3.9'
services:


  # Datadog Agent
  dd-agent:
    container_name: dd-agent
    image: datadog/agent:7.35.0
    env_file:
      - ~/sandbox.docker.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOG_LEVEL=TRACE
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AC_EXCLUDE=name:collector
      - DD_OTLP_GRPC_PORT=4317

  # Redis
  redis-cart:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}"

  # AdService
  adservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-adservice
    build:
      context: ./
      dockerfile: ./src/adservice/Dockerfile
    ports:
      - "${AD_SERVICE_PORT}"
    environment:
      - AD_SERVICE_PORT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=adservice
    depends_on:
      - dd-agent

  # CartService
  cartservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-cartservice
    build:
      context: ./
      dockerfile: ./src/cartservice/src/Dockerfile
    ports:
      - "${CART_SERVICE_PORT}"
    environment:
      - CART_SERVICE_PORT
      - REDIS_ADDR
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=cartservice
      - ASPNETCORE_URLS=http://*:${CART_SERVICE_PORT}
    depends_on:
      - redis-cart
      - dd-agent

  # CheckoutService
  checkoutservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-checkoutservice
    build:
      context: ./
      dockerfile: ./src/checkoutservice/Dockerfile
    ports:
      - "${CHECKOUT_SERVICE_PORT}"
    environment:
      - CHECKOUT_SERVICE_PORT
      - CART_SERVICE_ADDR
      - CURRENCY_SERVICE_ADDR
      - EMAIL_SERVICE_ADDR
      - PAYMENT_SERVICE_ADDR
      - PRODUCT_CATALOG_SERVICE_ADDR
      - SHIPPING_SERVICE_ADDR
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=checkoutservice
    depends_on:
      - cartservice
      - currencyservice
      - emailservice
      - paymentservice
      - productcatalogservice
      - shippingservice
      - dd-agent

  # CurrencyService
  currencyservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-currencyservice
    build:
      context: ./src/currencyservice
    ports:
      - "${CURRENCY_SERVICE_PORT}"
    environment:
      - PORT=${CURRENCY_SERVICE_PORT}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=currencyservice
    depends_on:
      - dd-agent

  # EmailService
  emailservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-emailservice
    build:
      context: ./src/emailservice
    ports:
      - "${EMAIL_SERVICE_PORT}"
    environment:
      - APP_ENV=production
      - PORT=${EMAIL_SERVICE_PORT}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=emailservice
    depends_on:
      - dd-agent

  # Frontend
  frontend:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-frontend
    build:
      context: ./
      dockerfile: ./src/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_ADDR
      - AD_SERVICE_ADDR
      - CART_SERVICE_ADDR
      - CHECKOUT_SERVICE_ADDR
      - CURRENCY_SERVICE_ADDR
      - PRODUCT_CATALOG_SERVICE_ADDR
      - RECOMMENDATION_SERVICE_ADDR
      - SHIPPING_SERVICE_ADDR
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=frontend
      - OTEL_EXPORTER_OTLP_ENDPOINT
    depends_on:
      - adservice
      - cartservice
      - checkoutservice
      - currencyservice
      - dd-agent
      - productcatalogservice
      - recommendationservice
      - shippingservice

  # PaymentService
  paymentservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-paymentservice
    build:
      context: ./
      dockerfile: ./src/paymentservice/Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT}"
    environment:
      - PAYMENT_SERVICE_PORT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=paymentservice
    depends_on:
      - dd-agent

  # ProductCatalogService
  productcatalogservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-productcatalogservice
    build:
      context: ./
      dockerfile: ./src/productcatalogservice/Dockerfile
    ports:
      - "${PRODUCT_CATALOG_SERVICE_PORT}"
    environment:
      - PRODUCT_CATALOG_SERVICE_PORT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=productcatalogservice
    depends_on:
      - dd-agent

  # RecommendationService
  recommendationservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-recommendationservice
    build:
      context: ./
      dockerfile: ./src/recommendationservice/Dockerfile
    ports:
      - "${RECOMMENDATION_SERVICE_PORT}"
    depends_on:
      - productcatalogservice
      - dd-agent
    environment:
      - RECOMMENDATION_SERVICE_PORT
      - PRODUCT_CATALOG_SERVICE_ADDR
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=recommendationservice

  # ShippingService
  shippingservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-shippingservice
    build:
      context: ./src/shippingservice
    ports:
      - "${SHIPPING_SERVICE_PORT}"
    environment:
      - PORT=${SHIPPING_SERVICE_PORT}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=shippingservice
    depends_on:
      - dd-agent

  # FeatureFlagService
  featureflagservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-featureflagservice
    build:
      context: ./src/featureflagservice
    ports:
      - "${FEATURE_FLAG_SERVICE_PORT}:${FEATURE_FLAG_SERVICE_PORT}"
      - "${FEATURE_FLAG_GRPC_SERVICE_PORT}"
    environment:
      - PORT=${FEATURE_FLAG_SERVICE_PORT}
      - GRPC_PORT=${FEATURE_FLAG_GRPC_SERVICE_PORT}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=featureflagservice
      - DATABASE_URL=ecto://ffs:ffs@ffs_postgres:5432/ffs
    depends_on:
      - ffs_postgres

  ffs_postgres:
    image: cimg/postgres:14.2
    environment:
      - POSTGRES_USER=ffs
      - POSTGRES_DB=ffs
      - POSTGRES_PASSWORD=ffs

  # LoadGenerator
  loadgenerator:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-loadgenerator
    build:
      context: ./
      dockerfile: ./src/loadgenerator/Dockerfile
    environment:
      - FRONTEND_ADDR
      - USERS
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://dd-agent:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=loadgenerator
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      - frontend

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./src/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "${PROMETHEUS_SERVICE_PORT}:${PROMETHEUS_SERVICE_PORT}"

  # Grafana
  grafana:
    image: grafana/grafana:9.0.1
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_SERVICE_PORT}:${GRAFANA_SERVICE_PORT}"
